dist: trusty
sudo: true
language: cpp

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-trusty-6.0
      - sourceline: "ppa:samuel-bachmann/boost"
    packages:
      - g++-6
      - llvm-6.0
      - clang-6.0
      - libboost1.60-all-dev

script:
  - cd "${TRAVIS_BUILD_DIR}"
  - CXX=clang++-6.0 CC=clang-6.0 cmake .
  - CXX=clang++-6.0 CC=clang-6.0 cmake --build . -- -j3

