dist: artful
sudo: false
language: cpp

addons:
  apt:
    sources:
      - sourceline: 'ppa:ubuntu-toolchain-r/test'
      - sourceline: 'deb http://apt.llvm.org/artful/ llvm-toolchain-artful-6.0 main'
        key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
    packages:
      - llvm-6.0
      - clang-6.0
      - boost
      - libboost1.63-all-dev

script:
  - CXX=clang++ CC=clang cmake .
  - cmake --build .


