dist: trusty
sudo: true
language: cpp
matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - sourceline: "ppa:samuel-bachmann/boost"
            - sourceline: "ppa:george-edison55/cmake-3.x"
          packages:
            - g++-7
            - libboost1.60-all-dev
            - cmake-data
            - cmake
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

before_install:
    - eval "${MATRIX_EVAL}"

script:
  - mkdir build-debug
  - cd build-debug
  - cmake -DCMAKE_INSTALL_PREFIX=../.. ..
  - cmake --build . -- -j3
  - ./service_test
  - cmake --build . -- install

