dist: trusty
sudo: true
language: cpp

before_install:
  - sudo apt-get remove -y binutils

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-trusty-6.0
      - debian-sid
    packages:
      - llvm-6.0
      - clang-6.0
      - libboost-all-dev

script:
  - cd "${TRAVIS_BUILD_DIR}"
  - CXX=clang++-6.0 CC=clang-6.0 cmake .
  - cmake --build . -- -j3

