dist: trusty
sudo: true
language: cpp
matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-6.0
            - sourceline: "ppa:samuel-bachmann/boost"
          packages:
            - clang-6.0
            - libboost1.60-all-dev
      env:
        - MATRIX_EVAL="CC=clang-6.0 && CXX=clang++-6.0"

before_install:
    - eval "${MATRIX_EVAL}"

script:
  - mkdir build-debug
  - cd build-debug
  - cmake -DCMAKE_INSTALL_PREFIX=../.. ..
  - cmake --build . -- -j3
  - ./service_test
  - cmake --build . -- install

