dist: artful
sudo: true
language: cpp

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libboost1.64-all-dev

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - sourceline: 'deb http://apt.llvm.org/artful/ llvm-toolchain-artful-6.0 main'
        key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
    packages:
      - llvm-6.0
      - clang-6.0
      - boost
      - libboost1.63-all-dev

script:
  - CXX=clang++ CC=clang cmake .
  - cmake --build .


