dist: trusty
sudo: true
language: cpp

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - sourceline: 'deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-6.0 main'
        key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
    packages:
      - llvm-6.0
      - clang-6.0
      - libboost-all-dev

script:
  - CXX=clang++ CC=clang cmake .
  - cmake --build . -- -j3


